branch-defaults:
  default:
    environment: ordering-system-dev2
    group_suffix: null
environment-defaults:
  ordering-system-dev2:
    branch: null
    repository: null
global:
  application_name: ordering-system
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: target/ordering-system-0.0.1-SNAPSHOT.jar
